import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'suppliers',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true },
        { name: 'name', type: 'string' },
        { name: 'code', type: 'string', isIndexed: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'address', type: 'string', isOptional: true },
        { name: 'area', type: 'string', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'metadata', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'products',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true },
        { name: 'name', type: 'string' },
        { name: 'code', type: 'string', isIndexed: true },
        { name: 'unit', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'metadata', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'collections',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true },
        { name: 'client_id', type: 'string', isIndexed: true },
        { name: 'user_id', type: 'number' },
        { name: 'supplier_id', type: 'string', isIndexed: true },
        { name: 'product_id', type: 'string', isIndexed: true },
        { name: 'quantity', type: 'number' },
        { name: 'unit', type: 'string' },
        { name: 'rate', type: 'number' },
        { name: 'amount', type: 'number' },
        { name: 'collection_date', type: 'number', isIndexed: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'metadata', type: 'string', isOptional: true },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'version', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'payments',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true },
        { name: 'client_id', type: 'string', isIndexed: true },
        { name: 'user_id', type: 'number' },
        { name: 'supplier_id', type: 'string', isIndexed: true },
        { name: 'collection_id', type: 'string', isOptional: true },
        { name: 'payment_type', type: 'string' },
        { name: 'amount', type: 'number' },
        { name: 'payment_date', type: 'number', isIndexed: true },
        { name: 'payment_method', type: 'string', isOptional: true },
        { name: 'reference_number', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'metadata', type: 'string', isOptional: true },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'version', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
